### ISSUE TITLE
UnhandledPromiseRejectionWarning Error Occurred when 'npm run test:devtools'

### ISSUE THREAD

**Issue by icelandld815** [pako88/wdio-mocha-typescript#5] opened 2020-09-15 03:06 UTC
**After i clone this project, run eslint and tried run command 'npm run test:devtools', below error happened:**

(node:67142) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined
    at TraceGatherer.onLoadEventFired (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/@wdio/devtools-service/build/gatherer/trace.js:117:67)
    at /Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (/Users/i065037/Documents/Innovation/wdio-mocha-typescript/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:215:7)
[0-1] (node:67142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by pako88** [comment] 2020-09-25 11:00
thanks for submitting this issue.
it is caused by npm package updates.
i currently don't have the time to look into this issue - feel free to create a MR with the fix.

**Comment by pako88** [comment] 2020-11-07 14:00
it is fixed now

**Closed by pako88** 2020-11-07 14:00 UTC
